### ISSUE TITLE
Prints in the benchmark code

### ISSUE THREAD

**Issue by djherbis** [daved/pythatchallenge#1]
Any idea why there are two prints in my benchmark? They lower my score.

https://github.com/daved/pythatchallenge/blob/4e65e049209b99e7d01988256e117a9aa0e9749b/main_bench_test.go#L29
https://github.com/daved/pythatchallenge/blob/4e65e049209b99e7d01988256e117a9aa0e9749b/main_bench_test.go#L54

**Comment by daved** [comment]
Using a global for benchmarking resulted in exceptionally low numbers.  The prints are remainders of investigating that behavior early on.  I apologize that my mistake has affected your results negatively.
